/* ============================================================
   CURRENTS · Playground — state-generated actions
   BUILD-SPEC §3.9. Derived from templates, not hand-authored per
   scenario, with `scenario.stateActions[state]` as an override
   hook that no scenario currently uses.

   The tone rule is load-bearing:
     ALLEVIATE reads unglamorously and carries low odds.
     AGGRAVATE reads like relief and carries high odds.
   If the destructive option looked destructive, the mechanic
   would teach nothing. The forecast is where the truth lives.
   ============================================================ */
import { FN } from './types.js';
import { ALLEVIATE, AGGRAVATE } from './model.js';
export { ALLEVIATE, AGGRAVATE };
import { RELIEF_VOICE, SPIRAL_VOICE, variantOf } from './corpus.js';

function pick(pool, i) { return pool[i % pool.length]; }

function makeAlleviate(target, carrier, blocked, i, stateTag) {
  const [label, detail] = pick(RELIEF_VOICE[target] || RELIEF_VOICE.se, i);
  return {
    id: `gen-alleviate-${stateTag}-${target}-${i}`,
    label, detail,
    signature: { [target]: ALLEVIATE.targetShare, [carrier]: 1 - ALLEVIATE.targetShare },
    intensity: ALLEVIATE.intensity,
    mandates: { serves: [`${target}.relief`], defers: [`${blocked}.pull`], violates: [] },
    origin: 'generated',
    axis: 'alleviate',
    template: `relief:${target}`,
  };
}

function makeAggravate(target, partner, blocked, i, stateTag) {
  const [label, detail] = pick(SPIRAL_VOICE[target] || SPIRAL_VOICE.ti, i);
  return {
    id: `gen-aggravate-${stateTag}-${target}-${i}`,
    label, detail,
    signature: { [target]: AGGRAVATE.targetShare, [partner]: 1 - AGGRAVATE.targetShare },
    intensity: AGGRAVATE.intensity,
    mandates: { serves: [`${target}.pull`], defers: [], violates: [`${blocked}.relief`] },
    origin: 'generated',
    axis: 'aggravate',
    template: `spiral:${target}`,
    /* the target function gets a real short-term pleasure bonus — this is
       exactly why a spiral is self-sustaining */
    pleasureBonus: AGGRAVATE.pleasureBonus,
    pleasureTarget: target,
  };
}

/**
 * @param {'loop'|'grip'} machine
 * @param {object} stack {dom,aux,tert,inf}
 * @param {object} scenario resolved scenario (for the override hook)
 * @returns {Array} two alleviating and two aggravating cards, in that order
 */
export function generateStateActions(machine, stack, scenario) {
  const override = scenario?.raw?.stateActions?.[machine];
  if (override) return override.map((a) => ({ ...a, origin: 'generated' }));

  const seed = variantOf(`${machine}:${stack.dom}${stack.aux}`);

  if (machine === 'loop') {
    /* alleviate: route work back to the BYPASSED auxiliary — the only thing
       that ends a loop. aggravate: feed the looping dom↔tert pair. */
    return [
      makeAlleviate(stack.aux, stack.dom, stack.dom, seed, 'loop'),
      makeAlleviate(stack.aux, stack.tert, stack.dom, seed + 1, 'loop'),
      makeAggravate(stack.dom, stack.tert, stack.aux, seed, 'loop'),
      makeAggravate(stack.tert, stack.dom, stack.aux, seed + 1, 'loop'),
    ];
  }

  if (machine === 'grip') {
    /* alleviate: back to the dominant and auxiliary. aggravate: feed the
       inferior, which is precisely what it is asking for. */
    return [
      makeAlleviate(stack.aux, stack.dom, stack.inf, seed, 'grip'),
      makeAlleviate(stack.dom, stack.aux, stack.inf, seed + 1, 'grip'),
      makeAggravate(stack.inf, stack.tert, stack.dom, seed, 'grip'),
      makeAggravate(stack.inf, stack.aux, stack.dom, seed + 1, 'grip'),
    ];
  }

  return [];
}

/** One line naming what the deck is doing, for the rail header. */
export function deckNote(machine, stack) {
  if (machine === 'loop') {
    return {
      title: 'action set — authored, plus two generated by the loop',
      sub: `2 alleviate (route work back to ${FN[stack.aux].label}) · 2 aggravate (feed ${FN[stack.dom].label}–${FN[stack.tert].label})`,
    };
  }
  if (machine === 'grip') {
    return {
      title: 'action set — the deck the grip wants you to see',
      sub: '2 alleviate · 2 aggravate · the aggravating ones look best, and that is the point',
    };
  }
  return {
    title: 'action set — hover to forecast, click to commit',
    sub: 'one commit ends this scenario',
  };
}
